#include <iostream.h>
#include <conio.h>

main()
{
int Bil1, Bil2;

cout<<"Masukkan Bilangan Pertama : ";cin>>Bil1;
cin>>Bil1;
cout<<"Masukkan bilangan kedua : ";cin>>Bil2;
cin>>Bil2;
cout<<"Hasil "<<Bil1<<" + "Bil2 <<" = "(Bil1+Bil2)
cout<<"Hasil "<<Bil1<<" - "Bil2<<" = "(Bil1-Bil2)
cout<<"Hasil "<<Bil1<<" * "Bil2<<" = "(Bil1*Bil2)
cout<<"Hasil "<<Bil1<<" / "Bil2<<" = "(Bi1/Bil2)
cout<<"Hasil "<<Bil1<<" % "Bil2<<" = "(Bil1%Bil2)
ch;
}


