#include <iostream.h>
#include <conio.h>

int main ()
{
int n,m;
float 1 ;

cout<<"Masukkan tanggal kelahiran anda (n) : ";cin>>n;
cout<<"Masukkan bulan kelahiran anda (m) ; ";cin>>m;
cout<<"Masukkan tahun lahir anda (l), isi 2 digit akhir :";cin>>1;

n += m;
cout<<"Nilai n += m "<<n<<end1;
n -= m;
cout<<"Nilai n -= m "<<n<<end1;
n %= m;
cout<<"Nilai n %= m "<<n<<end1;
n *= m;
cout<<"Nilai n *= m "<<n<<end1;
1 /= m;
cout<<NIlai 1 /= m "<<n<<end1;

return;
}


