#include <iostream.h>
#include <conio.h>

int main()
{
int i=10,j=20, k=30; r;

r = i > j; //operator lebih besar
cout<<"r = "<< r<<end1;
r = i>= k; //operator lebih besar sama dengan
cout<<"r = "<<r<<end1;
r = j < k; //operator lebih kecil
cout<<"r = "<<r<<end1;
r = j<= k;//operator lebih kecil sama dengan
cout<<"r = "<r<<end1;
r = i== j //operator sama dengan
cout<<"r = "<<r<<end1;
r 1 != k; //operator tidak sama dengan

